# SOPS configuration file
# This file configures how SOPS encrypts and decrypts secrets

# Keys for encryption/decryption
keys:
  # Age keys (recommended for NixOS)
  - &user_age age1hl7ldhs3tgk6j4y8rj9vd5j0yxlvgxb5jqrfj8l7z2kd0pv6q9s6e8r3n
  
  # GPG keys (alternative)
  # - &user_gpg 0x1234567890ABCDEF

# File encryption rules
creation_rules:
  # Default rule for all files in secrets/
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *user_age
        # pgp:
        #   - *user_gpg

  # Specific rules for different types of secrets
  - path_regex: secrets/production/.*\.yaml$
    key_groups:
      - age:
          - *user_age
        # pgp:
        #   - *user_gpg

  - path_regex: secrets/development/.*\.yaml$
    key_groups:
      - age:
          - *user_age
        # pgp:
        #   - *user_gpg